using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace converge_server.Migrations
{
    /// <inheritdoc />
    public partial class AddProductsAndPurchaseOrders : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: add ProductId column only if it doesn't already exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name='PurchaseRequestItems' AND column_name='ProductId'
                    ) THEN
                        ALTER TABLE ""PurchaseRequestItems"" ADD COLUMN ""ProductId"" integer;
                    END IF;
                END $$;
            ");

            // Products table: idempotent create
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Products"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Category"" text NOT NULL,
                    ""Subcategory"" text NOT NULL,
                    ""Brand"" text NOT NULL,
                    ""Model"" text NOT NULL,
                    ""ProductName"" text NOT NULL,
                    ""Specs"" text NOT NULL,
                    ""Price"" numeric NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_Products"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.CreateTable(
                name: "PurchaseOrders",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    BillOfMaterialId = table.Column<Guid>(type: "uuid", nullable: false),
                    SupplierId = table.Column<Guid>(type: "uuid", nullable: true),
                    PONumber = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    OrderDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    ExpectedArrivalDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    ShippingAddress = table.Column<string>(type: "text", nullable: false),
                    UntaxedAmount = table.Column<decimal>(type: "numeric", nullable: false),
                    VATAmount = table.Column<decimal>(type: "numeric", nullable: false),
                    DiscountAmount = table.Column<decimal>(type: "numeric", nullable: false),
                    GrandTotal = table.Column<decimal>(type: "numeric", nullable: false),
                    Status = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    Remarks = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PurchaseOrders", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PurchaseOrders_BillOfMaterials_BillOfMaterialId",
                        column: x => x.BillOfMaterialId,
                        principalTable: "BillOfMaterials",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "PurchaseOrderItems",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    PurchaseOrderId = table.Column<Guid>(type: "uuid", nullable: false),
                    BillOfMaterialItemId = table.Column<Guid>(type: "uuid", nullable: false),
                    ItemName = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Quantity = table.Column<int>(type: "integer", nullable: false),
                    Unit = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    UnitPrice = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    DiscountAmount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    VATAmount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    LineTotal = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    Remarks = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PurchaseOrderItems", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PurchaseOrderItems_BillOfMaterialItems_BillOfMaterialItemId",
                        column: x => x.BillOfMaterialItemId,
                        principalTable: "BillOfMaterialItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PurchaseOrderItems_PurchaseOrders_PurchaseOrderId",
                        column: x => x.PurchaseOrderId,
                        principalTable: "PurchaseOrders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // Idempotent index creation
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PurchaseRequestItems_ProductId"" ON ""PurchaseRequestItems"" (""ProductId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PurchaseOrderItems_BillOfMaterialItemId"" ON ""PurchaseOrderItems"" (""BillOfMaterialItemId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PurchaseOrderItems_PurchaseOrderId"" ON ""PurchaseOrderItems"" (""PurchaseOrderId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PurchaseOrders_BillOfMaterialId"" ON ""PurchaseOrders"" (""BillOfMaterialId"");");

            // Idempotent FK: add only if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints
                        WHERE constraint_name = 'FK_PurchaseRequestItems_Products_ProductId'
                    ) THEN
                        ALTER TABLE ""PurchaseRequestItems""
                            ADD CONSTRAINT ""FK_PurchaseRequestItems_Products_ProductId""
                            FOREIGN KEY (""ProductId"") REFERENCES ""Products""(""Id"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PurchaseRequestItems_Products_ProductId",
                table: "PurchaseRequestItems");

            migrationBuilder.DropTable(
                name: "Products");

            migrationBuilder.DropTable(
                name: "PurchaseOrderItems");

            migrationBuilder.DropTable(
                name: "PurchaseOrders");

            migrationBuilder.DropIndex(
                name: "IX_PurchaseRequestItems_ProductId",
                table: "PurchaseRequestItems");

            migrationBuilder.DropColumn(
                name: "ProductId",
                table: "PurchaseRequestItems");
        }
    }
}
